name: Build & Test

on: push

jobs:
  build-and-test:
    name: GitHub Build&Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Print info
      run: |
        echo User $GITHUB_ACTOR triggered build on $GITHUB_REF by $GITHUB_SHA commit.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Build sln
      run: dotnet build -c Release --no-cache ./HappyCode.NetCoreBoilerplate.sln

    - name: Test sln
      run: dotnet test -c Release --no-build ./HappyCode.NetCoreBoilerplate.sln
  
  collect-code-coverage:
    name: Code coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Collect code coverage
      run: dotnet test -c Release /p:CollectCoverage=true /p:CoverletOutput="../" /p:MergeWith="../coverage.json" /maxcpucount:1 /p:CoverletOutputFormat=\"json,opencover\" ./HappyCode.NetCoreBoilerplate.sln

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./test/coverage.opencover.xml
        flags: unittests
