name: Build & Test

on: push

jobs:
  skip-or-not:
    name: skip or not
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: skip or not
      uses: atlwendy/retrieve-commit-messages-from-pr@v3

    - name: output skip or not
      run: echo ::set-env name=SHOULD_RUN::${{ steps.skipornot.outputs.shouldRun }}
    
  build-and-test:
    name: GitHub Build&Test
    runs-on: ubuntu-latest
    if: {{ env.SHOULD_RUN }} == 'true'

    steps:    
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Build sln
      run: dotnet build -c Release --no-cache /clp:NoSummary ./HappyCode.NetCoreBoilerplate.sln

    - name: Test sln
      run: dotnet test -c Release --no-build --filter FullyQualifiedName!~LoadTests /maxcpucount:1 /p:WarningLevel=0 ./HappyCode.NetCoreBoilerplate.sln

  collect-code-coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    needs: [build-and-test]

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Collect code coverage
      run: dotnet test -c Release --filter FullyQualifiedName!~LoadTests /maxcpucount:1 /p:WarningLevel=0 /p:CollectCoverage=true /p:CoverletOutput="../" /p:MergeWith="../coverage.json" /p:CoverletOutputFormat=\"json,opencover\" ./HappyCode.NetCoreBoilerplate.sln

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./test/coverage.opencover.xml
        flags: unittests
