---
name: Build, Test, Code coverage

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [master]
    paths-ignore:
      - '**.md'

  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  TESTINGPLATFORM_TELEMETRY_OPTOUT: 1

jobs:
  build:
    name: dotnet Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Print info
        run: |
          echo User $GITHUB_ACTOR triggered build on $GITHUB_REF by $GITHUB_SHA commit.

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Build sln
        run: dotnet build ./HappyCode.NetCoreBoilerplate.slnx

      - name: Test architecture
        run: dotnet test --project ./test/HappyCode.NetCoreBoilerplate.ArchitecturalTests

  unit-tests:
    name: dotnet Unit tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Collect code coverage
        run: |
          dotnet test --filter-namespace "*UnitTests*" /p:WarningLevel=0 -- --coverage --coverage-output-format cobertura --coverage-output cobertura.xml

      - name: Generate report
        run: |
          dotnet tool install --ignore-failed-sources -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"**/cobertura.xml" -targetdir:"./test/coverage" -reporttypes:Cobertura -filefilters:"-*.g.cs"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./test/coverage/Cobertura.xml
          disable_search: true
          flags: unit

  integration-tests:
    name: dotnet Integration tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Collect code coverage
        run: |
          dotnet test --filter-namespace "*IntegrationTests*" /p:WarningLevel=0 -- --coverage --coverage-output-format cobertura --coverage-output cobertura.xml

      - name: Generate report
        run: |
          dotnet tool install --ignore-failed-sources -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"**/cobertura.xml" -targetdir:"./test/coverage" -reporttypes:Cobertura -filefilters:"-*.g.cs"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./test/coverage/Cobertura.xml
          disable_search: true
          flags: integration
